### ISSUE TITLE
Integration with HTML5 Canvas

### ISSUE THREAD

**Issue by ocyedwin** [asdfjkl/ctegaki-lib#1]
Hi, I would like to integrate your library (to recognize hand-written Japanese) with a web app through html5 canvas. Are you up for a paid assignment? anyway i can contact you?

**Comment by asdfjkl** [comment]
I have a full time job and do this just as a hobby - I am not up for paid
assignments. Programming a web-app is beyond what I can do on my spare
time.

But of course if you (or some other developer) want to go for it, i'll be
happy to answer questions or fix bugs of the lib.

regards

**Comment by asdfjkl** [comment]
If still relevant after all this time, see https://asdfjkl.github.io/kanjicanvas/ and https://github.com/asdfjkl/kanjicanvas (Implementation in client-side only Javascript). Ready to be embedded in other website.
